### PR TITLE
Switch from Rc to Arc

### PR DESCRIPTION
**Pull request by Chris-Hawblitzel**
When I originally created the `air`, `vir`, and `rust_verify` packages, I used `Rc` rather than `Arc`, thinking that we wouldn't need multiple threads.  Now I'm thinking that using `Rc` was short-sighted and that `Arc` will be more flexible.  (In particular, I'm starting to encounter situations where rustc calls multiple `rust_verify` callbacks, but not necessarily always in the same thread.)

### CODE REVIEW

**Comment by parno** [comment]
I'm certainly not opposed to swapping to `Arc` so that we're prepared for multi-threading.  I'm not sure I understand the current scenario, however.  Wouldn't each callback get its own thread-local storage?  The Dust code doesn't appear to have any global state that persists between callbacks, but I may be missing some.  Still learning to navigate Rust.

**Comment by Chris-Hawblitzel** [comment]
I think I will need to pass state from one callback to another soon to implement erasure.

**Comment by parno** [comment]
Ah, I see.  That makes sense.

**Review by parno — APPROVED** [review]

**Comment by utaal** [comment]
I'm not opposed, but this may be rather expensive from a performance perspective. Every time you clone or drop an `Arc`, you need a memory barrier, and those are slow. Here we'd be creating and dropping a bunch of these objects all the time, and we may end up stalling a lot. I don't want to do optimisations prematurely, but I'd also like to avoid a large refactor later on.
There's two solutions I can think of right now:
* we don't share handles to `Arc`s between threads, but instead send `Rc` between threads/callbacks via channels: this requires being able to relinquish ownership from one callback and transfer it to another (if, e.g., they are called sequentially)
or
* for everything that's immutable, we use a slab allocator for all the ast-like data-structures, without automatic reclamation; this is I think a similar strategy to what the compiler does, and can be _a lot cheaper_ (especially in multi-threaded scenarios). With a slab allocator, we cannot use the `Drop` trait, but I don't think we are using it right now. This may require capturing the lifetime of the slab in some of the data-structures.

If we want to go for the slab-allocator strategy, it may be worthwhile doing it now, as it may be trickier to retrofit later, but it's a bit hard to predict what the impact would be.

We can, and maybe should, punt on the performance concern altogether until it presents itself, of course. But we should expect this to be a potentially significant factor.

**Review by utaal — APPROVED** [review]

**Pull request merged**
