### PR TITLE
Design and initial support for immutable refs, and opaque datatypes

### PR DESCRIPTION
**Pull request by utaal**

### CODE REVIEW

**Comment by utaal** [comment]
@Chris-Hawblitzel what do you think about using `#[opaque]` instead of `#[verifier(no_verify)]` for structs? It sounds more natural to me, but maybe we want to avoid the association with fuel?

**Comment by Chris-Hawblitzel** [comment]
Right, I want to avoid the association with fuel.  Opaque already means something that can be revealed via the fuel mechanism (and selectively revealed, even within a single module or single function), and is used mainly for tuning verification performance.  But I'm open to other names besides opaque and no_verify.

**Comment by parno** [comment]
Thesaurus.com helpfully suggests: impenetrable, murky, nontransparent, and fuliginous :)  

This would break with Dafny, but what about using `hidden` for "can be revealed" (which actually seems like a more natural pairing), and then using `opaque` for something the verifier doesn't look inside.  In English, opaque is typically an inherent property, not something you can toggle.

**Comment by Chris-Hawblitzel** [comment]
Hidden has the advantage that it makes it more natural to unhide it (reveal).  It has the disadvantage that it sounds like the whole declaration is hidden, whereas opaque makes it clearer that the declaration is visible, and you just can't see inside it.

**Comment by parno** [comment]
Hmm, that's a good point.  "Cloaked"?  "Sealed"?  I'll keep thinking...

**Comment by utaal** [comment]
`abstract`, like `pub_abstract`?

**Comment by parno** [comment]
“Closed” and “Opened” instead of Opaque and Reveal?

**Comment by utaal** [comment]
I'm going to punt on figuring out the naming for now, and just use `#[verifier(no_verify)]` for this feature, that may turn out to be temporary.

**Comment by utaal** [comment]
Switched back to `#[verifier(no_verify)]` to always encode them as a `sort`, and added checks to `vir::well_formed`. I think this is now ready for review.
@Chris-Hawblitzel

**Review by Chris-Hawblitzel — APPROVED** [review]

**Pull request merged**
